### PR TITLE
Vp/fix/31/parse datetime

### LINKED ISSUE #31: ParseException at backend when trying to parse datetime fields

### PR DESCRIPTION
**Pull request by vyacheslav-pushkin**
Fixes https://github.com/cuba-platform/cuba-react/issues/31 and https://github.com/cuba-platform/cuba-react/issues/15

### CODE REVIEW

File: src/data/Instance.tsx [hunk 1]
```diff
@@ -53,18 +61,28 @@ export class DataInstanceStore<T> implements DataContainer {
...
             && typeof value === 'string') {
-        // @ts-ignore
         normalizedPatch[key] = {id: value};
       }
       if (propInfo && isToManyRelation(propInfo) && Array.isArray(value)) {
-        // @ts-ignore
         normalizedPatch[key] = value.map(id => ({id}));
       }
+      if (propInfo && isDateProperty(propInfo) && moment.isMoment(value)) {
+        const expectedFormat = 'YYYY-MM-DD';
```
Comment (web-devel) [inline src/data/Instance.tsx]: Let's just move constants to a separate file

**Review by web-devel — APPROVED** [review]
